# Generated by Django 5.1.6 on 2025-03-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(default='', max_length=150, verbose_name='Apellido')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Edad')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Título del libro')),
                ('cod', models.CharField(max_length=15, unique=True, verbose_name='Codigo')),
                ('author', models.ManyToManyField(to='prueba.author')),
            ],
        ),
    ]
